[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/livros"
  to = "/.netlify/functions/livros"
  status = 200

[[redirects]]
  from = "/api/arquivos/*"
  to = "/.netlify/functions/arquivos?key=:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
